"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SortitionModuleUniversity__factory = exports.KlerosCoreUniversity__factory = exports.ISortitionModuleUniversity__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ISortitionModuleUniversity__factory_js_1 = require("./ISortitionModuleUniversity__factory.js");
Object.defineProperty(exports, "ISortitionModuleUniversity__factory", { enumerable: true, get: function () { return ISortitionModuleUniversity__factory_js_1.ISortitionModuleUniversity__factory; } });
var KlerosCoreUniversity__factory_js_1 = require("./KlerosCoreUniversity__factory.js");
Object.defineProperty(exports, "KlerosCoreUniversity__factory", { enumerable: true, get: function () { return KlerosCoreUniversity__factory_js_1.KlerosCoreUniversity__factory; } });
var SortitionModuleUniversity__factory_js_1 = require("./SortitionModuleUniversity__factory.js");
Object.defineProperty(exports, "SortitionModuleUniversity__factory", { enumerable: true, get: function () { return SortitionModuleUniversity__factory_js_1.SortitionModuleUniversity__factory; } });
