"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BlockHashRNG__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var BlockHashRNG__factory_js_1 = require("./BlockHashRNG__factory.js");
Object.defineProperty(exports, "BlockHashRNG__factory", { enumerable: true, get: function () { return BlockHashRNG__factory_js_1.BlockHashRNG__factory; } });
