"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IForeignGateway__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract IERC20",
                name: "_token",
                type: "address",
            },
            {
                indexed: true,
                internalType: "bool",
                name: "_accepted",
                type: "bool",
            },
        ],
        name: "AcceptedFeeToken",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "bytes32",
                name: "_foreignBlockHash",
                type: "bytes32",
            },
            {
                indexed: true,
                internalType: "address",
                name: "_foreignArbitrable",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_foreignDisputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_choices",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
        ],
        name: "CrossChainDisputeOutgoing",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "contract IArbitrableV2",
                name: "_arbitrable",
                type: "address",
            },
        ],
        name: "DisputeCreation",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract IERC20",
                name: "_feeToken",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint64",
                name: "_rateInEth",
                type: "uint64",
            },
            {
                indexed: false,
                internalType: "uint8",
                name: "_rateDecimals",
                type: "uint8",
            },
        ],
        name: "NewCurrencyRate",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract IArbitrableV2",
                name: "_arbitrable",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_ruling",
                type: "uint256",
            },
        ],
        name: "Ruling",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
            {
                internalType: "contract IERC20",
                name: "_feeToken",
                type: "address",
            },
        ],
        name: "arbitrationCost",
        outputs: [
            {
                internalType: "uint256",
                name: "cost",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
        ],
        name: "arbitrationCost",
        outputs: [
            {
                internalType: "uint256",
                name: "cost",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_numberOfChoices",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
        ],
        name: "createDispute",
        outputs: [
            {
                internalType: "uint256",
                name: "disputeID",
                type: "uint256",
            },
        ],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_numberOfChoices",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
            {
                internalType: "contract IERC20",
                name: "_feeToken",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "_feeAmount",
                type: "uint256",
            },
        ],
        name: "createDispute",
        outputs: [
            {
                internalType: "uint256",
                name: "disputeID",
                type: "uint256",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
        ],
        name: "currentRuling",
        outputs: [
            {
                internalType: "uint256",
                name: "ruling",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "tied",
                type: "bool",
            },
            {
                internalType: "bool",
                name: "overridden",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "_disputeHash",
                type: "bytes32",
            },
        ],
        name: "disputeHashToForeignID",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "homeChainID",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "homeGateway",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "_messageSender",
                type: "address",
            },
            {
                internalType: "bytes32",
                name: "_disputeHash",
                type: "bytes32",
            },
            {
                internalType: "uint256",
                name: "_ruling",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "_forwarder",
                type: "address",
            },
        ],
        name: "relayRule",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "senderGateway",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "veaOutbox",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "_disputeHash",
                type: "bytes32",
            },
        ],
        name: "withdrawFees",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IForeignGateway__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IForeignGateway__factory = IForeignGateway__factory;
