services:
  settlr-foundry:
    image: ghcr.io/foundry-rs/foundry:latest
    working_dir: /workspace/contracts

    environment:
      GIT_CONFIG_COUNT: "1"
      GIT_CONFIG_KEY_0: "safe.directory"
      GIT_CONFIG_VALUE_0: "/workspace/contracts"

    volumes:
      - .:/workspace

    entrypoint: forge