"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionBatcher__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var TransactionBatcher__factory_js_1 = require("./TransactionBatcher__factory.js");
Object.defineProperty(exports, "TransactionBatcher__factory", { enumerable: true, get: function () { return TransactionBatcher__factory_js_1.TransactionBatcher__factory; } });
