"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IArbitrableV1__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract IArbitratorV1",
                name: "_arbitrator",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_ruling",
                type: "uint256",
            },
        ],
        name: "Ruling",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_ruling",
                type: "uint256",
            },
        ],
        name: "rule",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IArbitrableV1__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IArbitrableV1__factory = IArbitrableV1__factory;
