"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IEvidenceV1__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract IArbitratorV1",
                name: "_arbitrator",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_metaEvidenceID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_evidenceGroupID",
                type: "uint256",
            },
        ],
        name: "Dispute",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract IArbitratorV1",
                name: "_arbitrator",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_evidenceGroupID",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "_party",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "_evidence",
                type: "string",
            },
        ],
        name: "Evidence",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "_metaEvidenceID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "string",
                name: "_evidence",
                type: "string",
            },
        ],
        name: "MetaEvidence",
        type: "event",
    },
];
class IEvidenceV1__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IEvidenceV1__factory = IEvidenceV1__factory;
