[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@kleros/kleros-v2-contracts/=lib/kleros-v2-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]