"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KlerosCoreSnapshotProxy__factory = exports.IKlerosCore__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IKlerosCore__factory_js_1 = require("./IKlerosCore__factory.js");
Object.defineProperty(exports, "IKlerosCore__factory", { enumerable: true, get: function () { return IKlerosCore__factory_js_1.IKlerosCore__factory; } });
var KlerosCoreSnapshotProxy__factory_js_1 = require("./KlerosCoreSnapshotProxy__factory.js");
Object.defineProperty(exports, "KlerosCoreSnapshotProxy__factory", { enumerable: true, get: function () { return KlerosCoreSnapshotProxy__factory_js_1.KlerosCoreSnapshotProxy__factory; } });
