"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IHomeGateway__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "contract IArbitratorV2",
                name: "_arbitrator",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_arbitrableChainId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "_arbitrable",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_arbitrableDisputeID",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_arbitratorDisputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_externalDisputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_templateId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "string",
                name: "_templateUri",
                type: "string",
            },
        ],
        name: "CrossChainDisputeIncoming",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract IArbitratorV2",
                name: "_arbitrator",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_arbitratorDisputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_externalDisputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_templateId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "string",
                name: "_templateUri",
                type: "string",
            },
        ],
        name: "DisputeRequest",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract IArbitratorV2",
                name: "_arbitrator",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "_ruling",
                type: "uint256",
            },
        ],
        name: "Ruling",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "_disputeHash",
                type: "bytes32",
            },
        ],
        name: "disputeHashToHomeID",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "feeToken",
        outputs: [
            {
                internalType: "contract IERC20",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "foreignChainID",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "foreignGateway",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "receiverGateway",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "bytes32",
                        name: "foreignBlockHash",
                        type: "bytes32",
                    },
                    {
                        internalType: "uint256",
                        name: "foreignChainID",
                        type: "uint256",
                    },
                    {
                        internalType: "address",
                        name: "foreignArbitrable",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "foreignDisputeID",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "externalDisputeID",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "templateId",
                        type: "uint256",
                    },
                    {
                        internalType: "string",
                        name: "templateUri",
                        type: "string",
                    },
                    {
                        internalType: "uint256",
                        name: "choices",
                        type: "uint256",
                    },
                    {
                        internalType: "bytes",
                        name: "extraData",
                        type: "bytes",
                    },
                ],
                internalType: "struct IHomeGateway.RelayCreateDisputeParams",
                name: "_params",
                type: "tuple",
            },
            {
                internalType: "uint256",
                name: "_feeAmount",
                type: "uint256",
            },
        ],
        name: "relayCreateDispute",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "bytes32",
                        name: "foreignBlockHash",
                        type: "bytes32",
                    },
                    {
                        internalType: "uint256",
                        name: "foreignChainID",
                        type: "uint256",
                    },
                    {
                        internalType: "address",
                        name: "foreignArbitrable",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "foreignDisputeID",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "externalDisputeID",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "templateId",
                        type: "uint256",
                    },
                    {
                        internalType: "string",
                        name: "templateUri",
                        type: "string",
                    },
                    {
                        internalType: "uint256",
                        name: "choices",
                        type: "uint256",
                    },
                    {
                        internalType: "bytes",
                        name: "extraData",
                        type: "bytes",
                    },
                ],
                internalType: "struct IHomeGateway.RelayCreateDisputeParams",
                name: "_params",
                type: "tuple",
            },
        ],
        name: "relayCreateDispute",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_ruling",
                type: "uint256",
            },
        ],
        name: "rule",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "veaInbox",
        outputs: [
            {
                internalType: "contract IVeaInbox",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class IHomeGateway__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IHomeGateway__factory = IHomeGateway__factory;
