"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IHomeGateway__factory = exports.IForeignGateway__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IForeignGateway__factory_js_1 = require("./IForeignGateway__factory.js");
Object.defineProperty(exports, "IForeignGateway__factory", { enumerable: true, get: function () { return IForeignGateway__factory_js_1.IForeignGateway__factory; } });
var IHomeGateway__factory_js_1 = require("./IHomeGateway__factory.js");
Object.defineProperty(exports, "IHomeGateway__factory", { enumerable: true, get: function () { return IHomeGateway__factory_js_1.IHomeGateway__factory; } });
