"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IDisputeKit__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "_juror",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256[]",
                name: "_voteIDs",
                type: "uint256[]",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "_choice",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "string",
                name: "_justification",
                type: "string",
            },
        ],
        name: "VoteCast",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
        ],
        name: "areCommitsAllCast",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
        ],
        name: "areVotesAllCast",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_numberOfChoices",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
            {
                internalType: "uint256",
                name: "_nbVotes",
                type: "uint256",
            },
        ],
        name: "createDispute",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
        ],
        name: "currentRuling",
        outputs: [
            {
                internalType: "uint256",
                name: "ruling",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "tied",
                type: "bool",
            },
            {
                internalType: "bool",
                name: "overridden",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_nonce",
                type: "uint256",
            },
        ],
        name: "draw",
        outputs: [
            {
                internalType: "address",
                name: "drawnAddress",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_coreRoundID",
                type: "uint256",
            },
        ],
        name: "getCoherentCount",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_coreRoundID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_voteID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_feePerJuror",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_pnkAtStakePerJuror",
                type: "uint256",
            },
        ],
        name: "getDegreeOfCoherence",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_coreRoundID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_choice",
                type: "uint256",
            },
        ],
        name: "getRoundInfo",
        outputs: [
            {
                internalType: "uint256",
                name: "winningChoice",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "tied",
                type: "bool",
            },
            {
                internalType: "uint256",
                name: "totalVoted",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "totalCommited",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "nbVoters",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "choiceCount",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_coreRoundID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_voteID",
                type: "uint256",
            },
        ],
        name: "getVoteInfo",
        outputs: [
            {
                internalType: "address",
                name: "account",
                type: "address",
            },
            {
                internalType: "bytes32",
                name: "commit",
                type: "bytes32",
            },
            {
                internalType: "uint256",
                name: "choice",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "voted",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
        ],
        name: "isAppealFunded",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_coreDisputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_coreRoundID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_voteID",
                type: "uint256",
            },
        ],
        name: "isVoteActive",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class IDisputeKit__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IDisputeKit__factory = IDisputeKit__factory;
