"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IDisputeTemplateRegistry__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "_templateId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "string",
                name: "_templateTag",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "_templateData",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "_templateDataMappings",
                type: "string",
            },
        ],
        name: "DisputeTemplate",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "string",
                name: "_templateTag",
                type: "string",
            },
            {
                internalType: "string",
                name: "_templateData",
                type: "string",
            },
            {
                internalType: "string",
                name: "_templateDataMappings",
                type: "string",
            },
        ],
        name: "setDisputeTemplate",
        outputs: [
            {
                internalType: "uint256",
                name: "templateId",
                type: "uint256",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IDisputeTemplateRegistry__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IDisputeTemplateRegistry__factory = IDisputeTemplateRegistry__factory;
