"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISortitionModule__factory = exports.IEvidence__factory = exports.IDisputeTemplateRegistry__factory = exports.IDisputeKit__factory = exports.IArbitratorV2__factory = exports.IArbitrableV2__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IArbitrableV2__factory_js_1 = require("./IArbitrableV2__factory.js");
Object.defineProperty(exports, "IArbitrableV2__factory", { enumerable: true, get: function () { return IArbitrableV2__factory_js_1.IArbitrableV2__factory; } });
var IArbitratorV2__factory_js_1 = require("./IArbitratorV2__factory.js");
Object.defineProperty(exports, "IArbitratorV2__factory", { enumerable: true, get: function () { return IArbitratorV2__factory_js_1.IArbitratorV2__factory; } });
var IDisputeKit__factory_js_1 = require("./IDisputeKit__factory.js");
Object.defineProperty(exports, "IDisputeKit__factory", { enumerable: true, get: function () { return IDisputeKit__factory_js_1.IDisputeKit__factory; } });
var IDisputeTemplateRegistry__factory_js_1 = require("./IDisputeTemplateRegistry__factory.js");
Object.defineProperty(exports, "IDisputeTemplateRegistry__factory", { enumerable: true, get: function () { return IDisputeTemplateRegistry__factory_js_1.IDisputeTemplateRegistry__factory; } });
var IEvidence__factory_js_1 = require("./IEvidence__factory.js");
Object.defineProperty(exports, "IEvidence__factory", { enumerable: true, get: function () { return IEvidence__factory_js_1.IEvidence__factory; } });
var ISortitionModule__factory_js_1 = require("./ISortitionModule__factory.js");
Object.defineProperty(exports, "ISortitionModule__factory", { enumerable: true, get: function () { return ISortitionModule__factory_js_1.ISortitionModule__factory; } });
