"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IKlerosCoreRulerFragment__factory = exports.DisputeResolverRuler__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DisputeResolverRuler__factory_js_1 = require("./DisputeResolverRuler__factory.js");
Object.defineProperty(exports, "DisputeResolverRuler__factory", { enumerable: true, get: function () { return DisputeResolverRuler__factory_js_1.DisputeResolverRuler__factory; } });
var IKlerosCoreRulerFragment__factory_js_1 = require("./IKlerosCoreRulerFragment__factory.js");
Object.defineProperty(exports, "IKlerosCoreRulerFragment__factory", { enumerable: true, get: function () { return IKlerosCoreRulerFragment__factory_js_1.IKlerosCoreRulerFragment__factory; } });
