"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IBalanceHolderERC1155__factory = exports.IBalanceHolder__factory = exports.DisputeKitGated__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DisputeKitGated__factory_js_1 = require("./DisputeKitGated__factory.js");
Object.defineProperty(exports, "DisputeKitGated__factory", { enumerable: true, get: function () { return DisputeKitGated__factory_js_1.DisputeKitGated__factory; } });
var IBalanceHolder__factory_js_1 = require("./IBalanceHolder__factory.js");
Object.defineProperty(exports, "IBalanceHolder__factory", { enumerable: true, get: function () { return IBalanceHolder__factory_js_1.IBalanceHolder__factory; } });
var IBalanceHolderERC1155__factory_js_1 = require("./IBalanceHolderERC1155__factory.js");
Object.defineProperty(exports, "IBalanceHolderERC1155__factory", { enumerable: true, get: function () { return IBalanceHolderERC1155__factory_js_1.IBalanceHolderERC1155__factory; } });
