"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KlerosLiquidToV2Governor__factory = exports.IPinakion__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IPinakion__factory_js_1 = require("./IPinakion__factory.js");
Object.defineProperty(exports, "IPinakion__factory", { enumerable: true, get: function () { return IPinakion__factory_js_1.IPinakion__factory; } });
var KlerosLiquidToV2Governor__factory_js_1 = require("./KlerosLiquidToV2Governor__factory.js");
Object.defineProperty(exports, "KlerosLiquidToV2Governor__factory", { enumerable: true, get: function () { return KlerosLiquidToV2Governor__factory_js_1.KlerosLiquidToV2Governor__factory; } });
