"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DisputeResolver__factory = exports.ArbitrableExample__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ArbitrableExample__factory_js_1 = require("./ArbitrableExample__factory.js");
Object.defineProperty(exports, "ArbitrableExample__factory", { enumerable: true, get: function () { return ArbitrableExample__factory_js_1.ArbitrableExample__factory; } });
var DisputeResolver__factory_js_1 = require("./DisputeResolver__factory.js");
Object.defineProperty(exports, "DisputeResolver__factory", { enumerable: true, get: function () { return DisputeResolver__factory_js_1.DisputeResolver__factory; } });
