services:
  program-tester:
    build:
      context: ..
      dockerfile: docker/Dockerfile.txt

    working_dir: /workspace

    environment:
      TASK_ID: ${TASK_ID:-0}

    volumes:
      - ../program:/workspace/program
      - ../test-data:/workspace/test-data
      - ../runner:/workspace/runner

    command: python3 /workspace/runner/test_manager.py