"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UUPSProxy__factory = exports.UUPSProxiable__factory = exports.Initializable__factory = exports.klerosProxiesSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.klerosProxiesSol = __importStar(require("./KlerosProxies.sol/index.js"));
var Initializable__factory_js_1 = require("./Initializable__factory.js");
Object.defineProperty(exports, "Initializable__factory", { enumerable: true, get: function () { return Initializable__factory_js_1.Initializable__factory; } });
var UUPSProxiable__factory_js_1 = require("./UUPSProxiable__factory.js");
Object.defineProperty(exports, "UUPSProxiable__factory", { enumerable: true, get: function () { return UUPSProxiable__factory_js_1.UUPSProxiable__factory; } });
var UUPSProxy__factory_js_1 = require("./UUPSProxy__factory.js");
Object.defineProperty(exports, "UUPSProxy__factory", { enumerable: true, get: function () { return UUPSProxy__factory_js_1.UUPSProxy__factory; } });
