"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModeratedEvidenceModule__factory = exports.EvidenceModule__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var EvidenceModule__factory_js_1 = require("./EvidenceModule__factory.js");
Object.defineProperty(exports, "EvidenceModule__factory", { enumerable: true, get: function () { return EvidenceModule__factory_js_1.EvidenceModule__factory; } });
var ModeratedEvidenceModule__factory_js_1 = require("./ModeratedEvidenceModule__factory.js");
Object.defineProperty(exports, "ModeratedEvidenceModule__factory", { enumerable: true, get: function () { return ModeratedEvidenceModule__factory_js_1.ModeratedEvidenceModule__factory; } });
