"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IKlerosLiquid__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "contract IArbitrableV1",
                name: "_arbitrable",
                type: "address",
            },
        ],
        name: "AppealDecision",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "contract IArbitrableV1",
                name: "_arbitrable",
                type: "address",
            },
        ],
        name: "AppealPossible",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "contract IArbitrableV1",
                name: "_arbitrable",
                type: "address",
            },
        ],
        name: "DisputeCreation",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
        ],
        name: "appeal",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
        ],
        name: "appealCost",
        outputs: [
            {
                internalType: "uint256",
                name: "cost",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
        ],
        name: "appealPeriod",
        outputs: [
            {
                internalType: "uint256",
                name: "start",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "end",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
        ],
        name: "arbitrationCost",
        outputs: [
            {
                internalType: "uint256",
                name: "cost",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint96",
                name: "_subcourtID",
                type: "uint96",
            },
            {
                internalType: "uint256[4]",
                name: "_timesPerPeriod",
                type: "uint256[4]",
            },
        ],
        name: "changeSubcourtTimesPerPeriod",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_index",
                type: "uint256",
            },
        ],
        name: "courts",
        outputs: [
            {
                internalType: "uint96",
                name: "parent",
                type: "uint96",
            },
            {
                internalType: "bool",
                name: "hiddenVotes",
                type: "bool",
            },
            {
                internalType: "uint256",
                name: "minStake",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "alpha",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "feeForJuror",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "jurorsForCourtJump",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_choices",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "_extraData",
                type: "bytes",
            },
        ],
        name: "createDispute",
        outputs: [
            {
                internalType: "uint256",
                name: "disputeID",
                type: "uint256",
            },
        ],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
        ],
        name: "currentRuling",
        outputs: [
            {
                internalType: "uint256",
                name: "ruling",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
        ],
        name: "disputeStatus",
        outputs: [
            {
                internalType: "enum IArbitratorV1.DisputeStatus",
                name: "status",
                type: "uint8",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_index",
                type: "uint256",
            },
        ],
        name: "disputes",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint96",
                        name: "subcourtID",
                        type: "uint96",
                    },
                    {
                        internalType: "address",
                        name: "arbitrated",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "numberOfChoices",
                        type: "uint256",
                    },
                    {
                        internalType: "enum IKlerosLiquid.Period",
                        name: "period",
                        type: "uint8",
                    },
                    {
                        internalType: "uint256",
                        name: "lastPeriodChange",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "drawsInRound",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "commitsInRound",
                        type: "uint256",
                    },
                    {
                        internalType: "bool",
                        name: "ruled",
                        type: "bool",
                    },
                ],
                internalType: "struct IKlerosLiquid.Dispute",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "_destination",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "_amount",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "_data",
                type: "bytes",
            },
        ],
        name: "executeGovernorProposal",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
        ],
        name: "getDispute",
        outputs: [
            {
                internalType: "uint256[]",
                name: "votesLengths",
                type: "uint256[]",
            },
            {
                internalType: "uint256[]",
                name: "tokensAtStakePerJuror",
                type: "uint256[]",
            },
            {
                internalType: "uint256[]",
                name: "totalFeesForJurors",
                type: "uint256[]",
            },
            {
                internalType: "uint256[]",
                name: "votesInEachRound",
                type: "uint256[]",
            },
            {
                internalType: "uint256[]",
                name: "repartitionsInEachRound",
                type: "uint256[]",
            },
            {
                internalType: "uint256[]",
                name: "penaltiesInEachRound",
                type: "uint256[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint96",
                name: "_subcourtID",
                type: "uint96",
            },
        ],
        name: "getSubcourt",
        outputs: [
            {
                internalType: "uint256[]",
                name: "children",
                type: "uint256[]",
            },
            {
                internalType: "uint256[4]",
                name: "timesPerPeriod",
                type: "uint256[4]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_disputeID",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_appeal",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_voteID",
                type: "uint256",
            },
        ],
        name: "getVote",
        outputs: [
            {
                internalType: "address",
                name: "account",
                type: "address",
            },
            {
                internalType: "bytes32",
                name: "commit",
                type: "bytes32",
            },
            {
                internalType: "uint256",
                name: "choice",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "voted",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "_account",
                type: "address",
            },
        ],
        name: "jurors",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint256",
                        name: "stakedTokens",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "lockedTokens",
                        type: "uint256",
                    },
                ],
                internalType: "struct IKlerosLiquid.Juror",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "lockInsolventTransfers",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "minStakingTime",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "phase",
        outputs: [
            {
                internalType: "enum IKlerosLiquid.Phase",
                name: "",
                type: "uint8",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "pinakion",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class IKlerosLiquid__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IKlerosLiquid__factory = IKlerosLiquid__factory;
